web/timd/urls.py
from django.conf.urls import url, include

from django.contrib.auth import views as auth_views

import timd.views as views


actions_urlpatterns = [
    url(r'^delete/$', views.DeleteTask.as_view(), name='delete-task'),
    url(r'^update-deadline/$',
        views.UpdateDeadline.as_view(extra_context={'title': 'Update Deadline'}), name='update-deadline'),
    url(r'^unset-periodicity/$', views.UnsetPeriodicity.as_view(), name='unset-periodicity'),
    url(r'^set-reminder/$', views.SetReminder.as_view(extra_context={'title': 'Set Reminder'}), name='set-reminder'),
    url(r'^give-permission/$', views.GivePermission.as_view(), name='give-permission'),
    url(r'^withdraw-permission/(?P<user_id>[a-z0-9_-]+)/$',
        views.WithdrawPermission.as_view(), name='withdraw-permission'),
    url(r'^unset-reminder/(?P<reminder_id>\d+)/$', views.UnsetReminder.as_view(extra_context={'title': 'Unset Reminder'}), name='unset-reminder'),
    url(r'^attach-tag/$', views.AttachTag.as_view(), name='attach-tag'),
    url(r'^block/$', views.BlockTask.as_view(), name='block'),
    url(r'^complete/$', views.change_task_status, {'action': 'complete'}, name='complete'),
    url(r'^resume/$', views.change_task_status, {'action': 'resume'}, name='resume'),
    url(r'^archive/$', views.change_task_status, {'action': 'archive'}, name='archive'),
    url(r'^restore/$', views.change_task_status, {'action': 'restore'}, name='restore'),
    url(r'^detach-tag/(?P<tag_id>\d+)/$', views.DetachTag.as_view(), name='detach-tag'),
    url(r'^detach-relation/(?P<relation_id>\d+)/$', views.DetachRelation.as_view(), name='detach-relation'),
    url(r'^set-periodicity/$', views.SetPeriodicity.as_view(), name='set-periodicity'),
]


task_urlpatterns = [
    url(r'^$', views.Task.as_view(), name='task'),
    url(r'^/', include(actions_urlpatterns)),

    url(r'^create-subtask$',
        views.CreateSubtask.as_view(extra_context={'title': 'Create Subtask'}), name='create-subtask'),
    url(r'^(?P<subtask_title>[a-z0-9-_]+)/(?P<subtask_id>\d+)/$',
        views.Task.as_view(template_name='timd/subtask.html'), name='subtask'),
    #url(r'^(?P<subtask_title>[a-z0-9-_]+)/(?P<subtask_id>\d+)/', include(actions_urlpatterns)),
]


box_urlpatterns = [
    url(r'^rename/$', views.RenameBox.as_view(extra_context={'title': 'Rename Box'}), name='rename-box'),
    url(r'^delete/$', views.DeleteBox.as_view(extra_context={'title': 'Delete Box'}), name='delete-box'),

    #url(r'^(?P<task_title>[a-z0-9-_]+)/(?P<task_id>\d+)/', include(task_urlpatterns)),
    url(r'^$', views.Box.as_view(), name='box'),
]





profile_urlpatterns = [
   # url(r'^boxes/', include(boxes_urlpatterns)),
    url(r'^task-redirect/(?P<task_id>\d+)/', views.task_redirect, name='task-redirect'),
    url(r'^boxes/create/$', views.CreateBox.as_view(extra_context={'title': 'Create Box'}), name='create-box'),
    url(r'^notifications/$', views.Notifications.as_view(), name='notifications'),
    url(r'^shared/$', views.Shared.as_view(), name='shared'),
    url(r'^today/$', views.Today.as_view(), name='today'),
    url(r'^week/$', views.Week.as_view(), name='week'),
    url(r'^completed/$', views.Completed.as_view(), name='completed'),

    url(r'^boxes/(?P<box_title>[a-z0-9-_]+)/(?P<box_id>\d+)/tasks/create/$', views.CreateTask.as_view(extra_context={'title': 'Create Task'}), name='create-task'),
    url(r'^boxes/(?P<box_title>[a-z0-9-_]+)/(?P<box_id>\d+)/', include(box_urlpatterns)),
    url(r'^tasks/(?P<task_title>[a-z0-9-_]+)/(?P<task_id>\d+)/', include(task_urlpatterns)),

    url(r'^', views.Profile.as_view(), name='profile'),
]




app_name = 'timd'
urlpatterns = [
    url(r'^profiles/(?P<username>[a-z0-9_-]+)/', include(profile_urlpatterns)),
    url(r'^profile-redirect/$', views.profile_redirect, name='profile-redirect'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    url(r'^$', auth_views.LoginView.as_view(), name='login'),
]

web/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('timd.urls')),
    url(r'^admin/', admin.site.urls),
]

web/timd/forms.py
from django import forms


from dateutil import rrule

import timd.models as models


FREQUENCY = {
    'MINUTELY': rrule.MINUTELY,
    'HOURLY': rrule.HOURLY,
    'DAILY': rrule.DAILY,
    'WEEKLY': rrule.WEEKLY,
    'MONTHLY': rrule.MONTHLY,
    'YEARLY': rrule.YEARLY
}


WEEKDAY = {
    'MO': 0,
    'TU': 1,
    'WE': 2,
    'TH': 3,
    'FR': 4,
    'SA': 5,
    'SU': 6
}


class BoxForm(forms.ModelForm):
    class Meta:
        model = models.Box
        fields = ['title']


class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'priority']


class RelationForm(forms.ModelForm):
    class Meta:
        model = models.Relation
        fields = ['from_task', 'to_task', 'relation_type']


class CutRelationForm(forms.Form):
    related_task = forms.ModelChoiceField(queryset=models.Task.objects.all())
    type = forms.TypedChoiceField(required=True,
                                  choices=[(rel.value, rel.name) for rel in models.RelationType])


class TagForm(forms.ModelForm):
    class Meta:
        model = models.Tag
        fields = ['tag_text']


class DeadlineForm(forms.Form):
    deadline = forms.DateTimeField(required=False)
    #

#  "DD HH:MM:SS.uuuuuu"
class ReminderForm(forms.ModelForm):
    class Meta:
        model = models.Reminder
        fields = ['timedelta']



class PermissionForm(forms.ModelForm):
    class Meta:
        model = models.Permission
        fields = ['access_level', 'user']


class ConfirmDeleteAttributeForm(forms.Form):
    attribute_name = ''

    @property
    def confirm_question(self):
        return 'Do you wish to delete this {}?'.format(self.attribute_name)


class PeriodicityForm(forms.Form):

    freq = forms.TypedChoiceField(required=True,
                                  choices=[(FREQUENCY[key], key) for key in FREQUENCY],
                                  coerce=int)

    interval = forms.IntegerField(min_value=1, initial=1)
    count = forms.IntegerField(min_value=1, required=False)
    until = forms.SplitDateTimeField(input_date_formats=['%d.%m.%Y'], input_time_formats=['%H:%M'], required=False)
    byweekday = forms.TypedMultipleChoiceField(choices=[(WEEKDAY[key], key) for key in WEEKDAY],
                                               widget=forms.CheckboxSelectMultiple, required=False)

    def clean(self):
        cleaned_data = super(PeriodicityForm, self).clean()
        count = cleaned_data.get('count')
        until = cleaned_data.get('until')
        freq = cleaned_data.get('frequency')
        weekdays = cleaned_data.get('byweekday')

        if count is None and until is None:
            raise forms.ValidationError('Either count or until must be specified.')

        if count is not None and until is not None:
            raise forms.ValidationError('Cannot set both count and until options.')

        if freq == FREQUENCY['WEEKLY'] and not weekdays:
            self.add_error('byweekday', 'Specify weekdays when task should be repeated.')

        #if freq != FREQUENCY['WEEKLY'] and weekdays:
            #self.add_error('byweekday', 'Option is only available for weekly frequency.')

        return self.cleaned_data

class SearchForm(forms.Form):
    text = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}), required=True)

web/timd/views.py
import django
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
import django.views.generic.edit as generic_edit
import django.views as django_views
import django.views.generic.base as base

from datetime import datetime

import timd.forms as forms
import timd.models as models

from timd_lib.lib_api import LibraryAPI
from timd.db_api import DatabaseAPI


last_handle = None


def get_lib_api():
    storage_api = DatabaseAPI()
    return LibraryAPI(storage_api)


def get_current_task_id(kwargs):
    current_id = kwargs.get('subtask_id')
    if current_id is None:
        current_id = kwargs['task_id']

    return current_id


def profile_redirect(request):
    return HttpResponseRedirect(reverse('timd:profile', args=[request.user.username]))

import django.utils.timezone as timezone


def handle_overdue_terms(func):
    def wrapper(self, *args, **kwargs):
        self.lib_api.handle_overdue_terms(timezone.now())
        return func(self, *args, **kwargs)

    return wrapper


class ExtraContextMixin:
    extra_context = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.extra_context)
        return context


class LibAPIMixin:
    @property
    def lib_api(self):
        return LibraryAPI(DatabaseAPI())


def get_notifications_url(request):
    return 'http://' + request.META.get('HTTP_HOST') + reverse('timd:notifications', args=[request.user.username])




from datetime import timedelta
import pytz




class Profile(LibAPIMixin, base.TemplateView):


    #counter = 0
   # last_handle = None#datetime(2018, 9, 19, tzinfo=pytz.UTC)

    template_name = 'timd/profile.html'

    def get_context_data(self, **kwargs):
        if models.EMUL_NOW is None:
            models.EMUL_NOW = timezone.now() + timedelta(days=models.COUNTER)
        #ha = 'help'
        if self.request.META.get('HTTP_REFERER') == get_notifications_url(self.request):
            self.lib_api.view_notifications(self.kwargs['username'], models.EMUL_NOW)
        #    ha = 'cool'
        #if self.request.path == ''
       # if self.last_handle is not None and (timezone.now() - self.last_handle).min > 1:
           # self.counter += 1

        #self.lib_api.handle_overdue_terms(timezone.now() + timedelta(days=self.counter))
        if models.LAST is None or (timezone.now() - models.LAST).seconds > 30:
            models.LAST = timezone.now()
            models.COUNTER += 1
            models.EMUL_NOW = timezone.now() + timedelta(days=models.COUNTER)


        self.lib_api.handle_overdue_terms(models.EMUL_NOW)

        context = super().get_context_data(**kwargs)

        username = self.kwargs['username']
        shared_box, created_box, boxes = self.lib_api.get_user_boxes(username)

        context.update({
            'shared_box': shared_box,
            'created_box': created_box,
            'boxes': boxes,
            'created_tasks': self.lib_api.get_tasks_from_box(created_box),
            'path': self.request.META.get('HTTP_REFERER') + " " + get_notifications_url(self.request),
            'lst': models.LAST,
            'fuck': timezone.now(),
            'count': models.COUNTER,
            'delta': (timezone.now() - models.LAST).seconds,
            'emul_now': models.EMUL_NOW
        })

        return context


class Box(Profile):
    template_name = 'timd/box.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        box = self.lib_api.get_box_by_id(self.kwargs['box_id'])
        context.update({
            'box': box,
            'tasks_list': box.tasks.all(),
           # 'path': self.request.META.get('HTTP_REFERER')
        })

        return context


def get_task_context(lib_api, **kwargs):
    current_task_slug = get_current_task_id(kwargs)

    username = kwargs['username']

    current_task = lib_api.get_task_by_id(current_task_slug)

    #blocking, simultaneous, blocked = lib_api.get_all_user_relations(username, current_task)

    context = {
        'access_level': lib_api.get_permission(username, current_task).access_level,
        'current': current_task,
        'relations': lib_api.get_all_user_relations(username, current_task),
        'reminders': lib_api.get_reminders(current_task),
        'reminders_str': len(lib_api.get_reminders(current_task)),
        'permissions': lib_api.get_task_permissions(current_task),
     #   'blocking_tasks': blocking,#lib_api.get_blocking_tasks(username, current_task),
        #'blocked_tasks': blocked,#lib_api.get_blocked_tasks(username, current_task),
       # 'simultaneous_tasks': simultaneous,#lib_api.get_simultaneous_tasks(username, current_task),
        'tags': lib_api.get_user_tags(username, current_task),
        'subtasks': lib_api.get_all_subtasks(current_task),
        'form': forms.SearchForm()
    }

    #if current_task.parent is None:
    #    context.update({'subtasks': lib_api.get_subtasks(username, current_task)})
    return context


class Task(Profile):
    template_name = 'timd/task.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_task_context(self.lib_api, **self.kwargs))
        #context['path'] = self.request.META.get('HTTP_REFERER')

        return context


class Notifications(Profile):
    template_name = 'timd/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'page_slug': 'notifications',
            'title': 'Notifications',
            'a': 'hate it',
            'notifications': self.lib_api.get_all_user_notifications(self.kwargs['username']),
            #'path': self.request.META.get('HTTP_REFERER')
        })

        #self.lib_api.view_notifications(context['notifications'])

        return context


class Shared(Profile):
    template_name = 'timd/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'page_slug': 'shared-with-me',
            'title': 'Shared with me',
            'tasks_list': self.lib_api.get_shared_tasks(self.kwargs['username']),
           # 'path': self.request.META.get('HTTP_REFERER')
        })

        return context



class Today(Profile):
    template_name = 'timd/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = timezone.now().date()
        context.update({
            'page_slug': 'today',
            'title': 'Today',
            'now' : now,
            'tasks_list': self.lib_api.get_tasks_for_date(self.kwargs['username'], now)
           # 'path': self.request.META.get('HTTP_REFERER')
        })

        return context



class Week(Profile):
    template_name = 'timd/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = timezone.now().date()
        context.update({
            'page_slug': 'week',
            'title': 'Week',
            'now' : now,
            'tasks_list': self.lib_api.get_tasks_in_date_range(self.kwargs['username'], now, now+timedelta(days=7))
           # 'path': self.request.META.get('HTTP_REFERER')
        })

        return context


class Completed(Profile):
    template_name = 'timd/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'page_slug': 'completed',
            'title': 'Completed',
            'tasks_list': self.lib_api.get_user_completed_tasks(self.kwargs['username']),
            #'path': self.request.META.get('HTTP_REFERER')
        })

        return context


class RedirectMixin(LibAPIMixin, ExtraContextMixin):
    redirect_url_name = None

    def get_redirect_url_name(self):
        return self.redirect_url_name

    def redirect(self):
        return HttpResponseRedirect(reverse(self.get_redirect_url_name(), kwargs=self.kwargs))

    def redirect_back(self):
        return HttpResponseRedirect(self.request.path)

    def update_kwargs_redirect(self, **kwargs):
        self.kwargs.update(kwargs)
        return self.redirect()

    def pop_kwargs_redirect(self):
        if 'subtask_id' in self.kwargs:
            self.kwargs.pop('subtask_title')
            self.kwargs.pop('subtask_id')

        elif 'task_id' in self.kwargs:
            self.kwargs.pop('task_title')
            self.kwargs.pop('task_id')

        else:
            self.kwargs.pop('box_title')
            self.kwargs.pop('box_id')

        return self.redirect()

    def pop_and_update_redirect(self, *pop_args, **update_kwargs):
        for arg in pop_args:
            self.kwargs.pop(arg)

        self.kwargs.update(update_kwargs)
        #self.kwargs.pop('box_title')
        #self.kwargs.pop('box_id')

        return self.redirect()


class CreateBox(RedirectMixin, generic_edit.CreateView):
    form_class = forms.BoxForm
    template_name = 'timd/form.html'
    redirect_url_name = 'timd:profile'

    def form_valid(self, form):
        self.lib_api.create_box(self.kwargs['username'], form.cleaned_data['title'])
        return self.redirect()


class RenameBox(RedirectMixin, generic_edit.UpdateView):
    form_class = forms.BoxForm
    model = models.Box
    template_name = 'timd/form.html'
    redirect_url_name = 'timd:box'

    def get_object(self, queryset=None):
        return self.lib_api.get_box_by_id(self.kwargs['box_id'])

    def form_valid(self, form):
        box = self.lib_api.rename_box(self.object, form.cleaned_data['title'])
        return self.update_kwargs_redirect(box_title=box.title_slug)


class DeleteBox(RedirectMixin, generic_edit.DeleteView):
    model = models.Box
    template_name = 'timd/confirm_delete.html'
    redirect_url_name = 'timd:profile'

    def get_object(self, queryset=None):

web/timd/templates/timd/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset='utf-8' />
		<link rel="stylesheet" type="text/css" href="{% static 'timd/login_style.css' %}" />
		<title>{% block title %}Default{% endblock %}</title>
	</head>
	<body class="container">
		<div>{% block content %}{% endblock %}</div>
		<!--div>Footer</div-->
	</body>
</html>

web/timd/templates/timd/box.html
{% extends "timd/profile.html" %}
{% load static %}

{% block insides_title %}
<ul class="dropdown-menu">
   <li>
	   <a href="#"><h1>{{ box.title }}</h1></a>
	   <ul class="dropdown-menu-inner">
		   <li><a href="{% url 'timd:rename-box' username box.title|slugify box.id %}">Rename</a></li>
		   <li><a href="{% url 'timd:delete-box' username box.title|slugify box.id %}">Delete</a></li>
	   </ul>
   </li>
</ul>
{% endblock %}

{% block insides_content %}
<ul class="menu-button">
	    <li>
			<div>
                <ul class="horizontal-button">
				    <li class="long-long"><h3>Tasks</h3></li>
					<li class="narrow-action-ref">
						<a href="{% url 'timd:create-task' username box.title|slugify box.id %}"><h3>+</h3></a>
					</li>			
                </ul>
           </div>
		</li>
	</ul>
<div>
                        
                        </div>
<div>
	<h1>{{ aaa }}</h1>
   
	<ul class="base-menu">
    {% for task in box.tasks.all %}
        <li class="task"><a href="{% url 'timd:task' username task.title|slugify task.id %}">{{ task.title }}</a></li>
    {% endfor %}
    </ul>
</div>

{% endblock %}

web/timd/templates/timd/subtask.html
{% extends "timd/profile.html" %}

{% block insides_title %}

<ul class="dropdown-menu">
   <li>
	   <a href="#"><h1>{{ current.title }}</h1></a>
	   <ul class="dropdown-menu-inner">
		   
		   <li><a href="{% url 'timd:delete-task' username box_title box_id current.title|slugify current.id %}">Delete</a></li>
	   </ul>
   </li>
</ul>

{% endblock %}

{% block insides_content %}

<div>
    <ul class="horizontal-menu">
	{% if access_level <= EXECUTOR %}	
	    <li>
        {% if current.status == COMPLETED %}
	        <a href="{% url 'timd:resume' username box_title box_id task_title task_id current.title|slugify current.id  %}">Resume</a>
        {% else %}
            <a href="{% url 'timd:complete' username box_title box_id task_title task_id current.title|slugify current.id  %}">Complete</a>
        {% endif %}
        </li>
    {% endif %}
    {% if access_level <= CREATOR %}
	    <li>
	    {% if current.archived %}
	        <a href="{% url 'timd:restore' username box_title box_id task_title task_id current.title|slugify current.id  %}">Restore</a>
	    {% else %}
	        <a href="{% url 'timd:archive' username  box_title box_id task_title task_id current.title|slugify current.id  %}">Archive</a>
	    {% endif %}
	    </li>
	    <li><a href="{% url 'timd:delete-task' username box_title box_id task_title task_id current.title|slugify current.id  %}">Delete</a></li>
	{% endif %}
    </ul>
</div>
{% if access_level <= CREATOR %}
<a href="{% url 'timd:update-deadline' username box_title box_id task_title task_id current.title|slugify current.id  %}">Update deadline</a>
<a href="{% url 'timd:set-periodicity' username box_title box_id task_title task_id current.title|slugify current.id  %}">Set periodicity</a>
<a href="{% url 'timd:set-reminder' username box_title box_id task_title task_id current.title|slugify current.id %}">Set reminder</a>
<a href="{% url 'timd:unset-periodicity' username box_title box_id task_title task_id current.title|slugify current.id  %}">Unset periodicity</a>
{% endif %}

<a href="{% url 'timd:block' username box_title box_id task_title task_id current.title|slugify current.id  %}">Block</a>
<a href="{% url 'timd:attach-tag' username box_title box_id task_title task_id current.title|slugify current.id  %}">Attach tag</a>
{% if access_level <= ADMIN %}
<a href="{% url 'timd:give-permission' username box_title box_id task_title task_id current.title|slugify current.id  %}">Give permission</a>
{% endif %}

<div>
    {% include "timd/task_info.html" with task=current %}
</div>

{% endblock %}

web/timd/templates/timd/task_info.html
<div>
	
	<div class="task-info">
		<ul class="menu-button">
	        <li>
				<div>
					
					<ul class="horizontal-button">
						<li class="short-descr"><h3>Deadline</h3></li>
						<li class="cont"><p>{{ task.deadline }}</p></li>
						<li class="narrow-action-ref" >
						    {% if access_level <= CREATOR %}
                                <a href="{% url 'timd:update-deadline' username current.title|slugify current.id  %}"><h3>v</h3></a>
                            {% endif %}
						</li>					
                    </ul>
                    
                </div>
		    </li>
		    <li>	
			    <div>
					
					<ul class="horizontal-button">
						<li class="short-descr"><h3>Status</h3></li>
						<li class="cont"><p>{{ task.status }}</p></li>
						<li class="narrow-action-ref">
							{% if access_level <= EXECUTOR %}	
	    
                                {% if current.status == COMPLETED %}
									<a href="{% url 'timd:resume' username current.title|slugify current.id %}"><h3>v</h3></a>
								{% else %}
									<a href="{% url 'timd:complete' username current.title|slugify current.id  %}"><h3>v</h3></a>
								{% endif %}
        
							{% endif %}
						</li>			
                   </ul>
                   
               </div>
		    </li>
		    <li>		
				<div>
					
					<ul class="horizontal-button">
						<li class="short-descr"><h3>Priority</h3></li>
						<li class="cont"><p>{{ task.priority }}</p></li>
						<li class="narrow-action-ref" >
							<a href="{% url 'timd:block' username current.title|slugify current.id  %}"><h3>v</h3></a>
						</li>							
                    </ul>
                    
                </div>
		    </li>
		    <li>		
				<div>
					
					<ul class="horizontal-button">
						<li class="short-descr"><h3>Periodicity</h3></li>
						<li class="cont"><p>{{ task.periodicity }}</p></li>
						<li class="narrow-action-ref" > 							
								<a href="{% url 'timd:set-periodicity' username current.title|slugify current.id  %}"><h3>v</h3></a>
						</li>
							
                    </ul>
                    
                </div>
			</li>
		</ul>
	</div>
	
	<div>
		<ul class="menu-button">	
			<li>			
				<div>
					
					<ul class="horizontal-button">
						<li class="long-long"><h3>Reminders</h3></li>
						<li class="narrow-action-ref">
							<a href="{% url 'timd:set-reminder' username current.title|slugify current.id  %}"><h3>+</h3></a>
						</li>						
                    </ul>
                    
                </div>
			</li>
		</ul>                     
	</div>
	
    <div>
		<ul class="menu-button">
		{% for reminder in reminders %}
			<li>	
				<div>
					<ul class="horizontal-button">							
						<li class="reminder"><p>{{ reminder.term }} {{ reminder.timedelta }}</p></li>
						<li class="narrow-action-ref">
					        {% if access_level <= CREATOR %}
								<a href="{% url 'timd:unset-reminder' username current.title|slugify current.id reminder.id %}"><h3>x</h3></a>
							{% endif %}							
						</li>						
                    </ul>
                </div>
			</li>
		{% endfor %}	
		</ul>
	</div>


    <div>
	    <ul class="menu-button">
			<li>	
				<div>
					
					<ul class="horizontal-button">
						<li class="long-long"><h3>Related Tasks</h3></li>
						<li class="narrow-action-ref">
							<a href="{% url 'timd:block' username current.title|slugify current.id %}"><h3>+</h3></a>
						</li>					
                    </ul>
                 
                </div>           
			</li>
		</ul>                       
	</div>
	
    <div>
		<ul class="tag-menu">
		{% for rel_task in relations %}   
			<li>
				<div>
					<ul class="horizontal-button">		
						<li class="access-level">{{ rel_task.relation_type }}</li>					
						<li class="related-task">					
						{% if rel_task.to_task == task %}
							<a href="{% url 'timd:task' username rel_task.from_task.title_slug rel_task.from_task.id %}">{{ rel_task.from_task.title }}</a>
						{% else %}
							<a href="{% url 'timd:task' username rel_task.to_task.title_slug rel_task.to_task.id %}">{{ rel_task.to_task.title }}</a>
						{% endif %}
						</li>
						<li class="detach-ref">
							<a href="{% url 'timd:detach-relation' username task.title_slug task.id rel_task.id %}">x</a>
						</li>					
                    </ul>
                </div>
			</li>
		{% endfor %}
		</ul>
	</div>


	
	{% if access_level <= ADMIN %}
	<div>
		<ul class="menu-button">
			<li>	
				<div>
					<ul class="horizontal-button">
						<li class="long-long"><h3>Permissions</h3></li>
						<li class="narrow-action-ref">
							<a href="{% url 'timd:give-permission' username task.title_slug task.id %}"><h3>+</h3></a>
						</li>						
                    </ul>
                </div>
			</li>
		</ul>                    
    </div>
    {% endif %}
    
    <div>
		<ul class="tag-menu">
		{% for permission in permissions %}
			<li class="permission">		
				<div>
					<ul class="horizontal-button">
						<li class="access-level">{{ permission.access_level }}</li>
						<li class="tag-text">{{ permission.user }}</li>
						<li class="detach-ref"> 
							<a href="{% url 'timd:withdraw-permission' username task.title|slugify task.id permission.user.user.username %}">x</a>
						</li>					
                    </ul>
                </div>
			</li>
		{% endfor %}
		</ul>
	</div>

	<div>
		<ul class="menu-button">
			<li>			
				<div>
					<ul class="horizontal-button">
						<li class="long-long"><h3>Tags</h3></li>
						<li class="narrow-action-ref">
							<a href="{% url 'timd:attach-tag' username task.title|slugify task.id %}"><h3>+</h3></a>
						</li>						
					</ul>
            </div>
			</li>
		</ul>                     
    </div>
    
	<div>
		<ul class="tag-menu">
		{% for tag in tags %}
			<li>
			
				<div>
					<ul class="horizontal-button">
						<li class="tag-text">{{ tag.tag_text }}</li>
						<li class="detach-ref">
							<a href="{% url 'timd:detach-tag' username task.title|slugify task.id tag.id %}">x</a>
						</li>						
                    </ul>
                </div>
			</li>
		{% endfor %}
		</ul>
	</div>
	
</div>